# .goreleaser.yml file
# injest - another ConAcademy joint
# Copyright (c) 2023 Neomantra BV
# Documentation at http://goreleaser.com

project_name: injest

before:
  hooks:
    - go mod tidy

builds:
  - main: cmd/injest/main.go
    id: injest
    binary: injest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: injest
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

release:
  github:
    owner: conacademy
    name: injest

brews:
  - homepage: https://github.com/conacademy/injest
    description: "CLI Joke Wrapper"
    folder: Formula
    tap:
      owner: conacademy
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaserbot@neomantra.net
    install: |
      bin.install "injest"
